#investments-csf:
#  build:
#    context: .
#    dockerfile: Dockerfile-localdev
#  ports:
#    - "8080:8080"
#  depends_on:
#    - db

db:
  image: mongo:3.2
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/data/mongodb.log
  expose:
    - "27017"
  ports:
    - "27017:27017"
  volumes:
    - ./data/db:/data/db
    - ./data/configdb:/data/configdb

